config/routes.rb
Ragnarok2::Engine.routes.draw do
  scope "/:locale/games/ro2" do
        scope ":game_locale",
          #https://github.com/rails/rails/issues/7144
          #:defaults => {:game_locale => "en"},
          :only => [:index, :show] do

          resources :quests, :items, :citizens, :maps,
                    :item_sets, :dungeons, :kharas

          resources :citizen_drops,
                      :path=>"drops",
                      :only=>[:new, :destroy, :create],
                      :as => :drops do
            collection do
              post 'search'
            end
            member do
              post 'vote'
            end
          end

          resources :skill_groups, :path=>"skills"
          
          resources :item_categories, :only => :show

          resources :news

          match "exp" => "exp#index", :as => :exp_overview
        end
        scope ":game_locale" do
          match "/" => "dashboard#start", :as => :localized_root
        end
        match "/" => "dashboard#localize", :as => :root
  end
end

app/models/ragnarok2/base_exp.rb
module Ragnarok2
  class BaseExp < ActiveRecord::Base
    validates :base_level,
        :uniqueness => { :case_sensitive => false },
        :allow_blank => false,
        :numericality => { :only_integer => true }

    validates :base_exp_next, :npc_base_exp, :pro_exp_next, 
        :presence=>true, :numericality => { :only_integer => true }
  end
end

app/models/ragnarok2/citizen.rb
module Ragnarok2
  class Citizen < ActiveRecord::Base
    searchable
    
    validates :citizen_id,
        :uniqueness => { :case_sensitive => false },
        :allow_blank => false,
        :numericality => { :only_integer => true }

    validates :name, :presence => true

    default_scope includes(:name)
    belongs_to :name,
            :foreign_key => :string_name_id,
            :primary_key => :citizen_id,
            :class_name => "Ragnarok2::Translations::CitizenName"

    default_scope includes(:job_name)
    belongs_to :job_name,
            :foreign_key => :string_job_name_id,
            :primary_key => :citizen_id,
            :class_name => "Ragnarok2::Translations::CitizenJobName"

    has_many :quest_citizens, :dependent => :destroy
    has_many :quests, :through => :quest_citizens

    has_many :start_quests,
            :through => :quest_citizens,
            :class_name => "Ragnarok2::Quest",
            :source => :quest,
            :conditions => ["ragnarok2_quest_citizens.is_start = ?", true]

    has_many :citizen_items, :dependent => :destroy
    has_many :sellitems,
            :through => :citizen_items,
            :class_name => "Ragnarok2::Item",
            :source => :item

    has_many :citizen_drops,
            :dependent => :destroy
    has_many :dropitems,
            :through => :citizen_drops,
            :class_name => "Ragnarok2::Item",
            :source => :item

    has_many :spawn_points,
        :primary_key => :citizen_id,
        :dependent => :destroy

    has_many :maps, :through => :spawn_points
            

    after_save :update_function_information

    alias_method :drops, :citizen_drops


    scope :default_order, order("ragnarok2_citizens.min_level ASC, ragnarok2_translations_citizen_names.translation ASC")

    scope :search_by_name, lambda {|q|
        joins{name.inner}.where{name.translation =~ "%#{q}%"}
    }

    search_for :name, :as => :string do |b, q|
        b.joins{name.inner}.where{name.translation =~ "%#{q}%"}
    end
    search_for :min_level, :as => :integer do |b, q|
        b.where{min_level.gteq q}
    end
    search_for :max_level, :as => :integer do |b, q|
        b.where{max_level.lteq q}
    end

    def items
        self.dropitems+self.sellitems
    end

    def to_s
      "#{self.name}"
    end

    def to_param
      "#{self.id}-#{self.name.to_s.parameterize}"
    end

    def resistances
        [
            [:water, self.water_resist],
            [:earth, self.earth_resist],
            [:fire, self.fire_resist],
            [:wind, self.wind_resist],
            [:poison, self.poison_resist],
            [:saint, self.saint_resist],
            [:dark, self.dark_resist],
            [:psychokinesis, self.psychokinesis_resist],
            [:death, self.death_resist],
        ].delete_if{|k,v| v.zero?}
    end

    def exp
        exp = BaseExp.where(:base_level=>[self.min_level, self.max_level])
        exp.collect{|e| e.npc_base_exp}
    end

    private
    def function_information_changed?
      1.upto(3) do |i|
        return true if self.send("function_id_#{1}_changed?") || self.send("function_type_#{1}_changed?")
      end
    end


    def update_function_information(force=false)
        return unless force || function_information_changed?

        #delete all function information
        self.citizen_items.destroy_all
        #readd all function information
        1.upto(3) do |i|
            case self.send("function_type_#{i}")
            when 11 #merchant
                entries = MerchantInfo.where(:merchant_function_id=>self.send("function_id_#{i}"))
                entries.each do |e|
                    item = Item.where(:item_id=>e.item_id).first
                    next unless item
                    self.citizen_items.create(
                        :item=>item, :max=>e.max,
                        :buy_type=>e.buy_type
                    )
                end
            end
        end
    end
  end
end

app/models/ragnarok2/citizen_drop.rb
module Ragnarok2
  class CitizenDrop < ActiveRecord::Base

    belongs_to :item, :inverse_of => :citizen_drops
    belongs_to :citizen, :inverse_of => :citizen_drops

    validates :item, :citizen, :presence => true

    default_scope includes(:citizen_drop_users)
    has_many :citizen_drop_users,
          :dependent => :destroy
    has_many :users,
          :through => :citizen_drop_users

    alias_method :votes, :citizen_drop_users

    scope :default_order, order("approving_users_count DESC, disapproving_users_count ASC")

    def update_user_counter_cache!
      self.update_attributes(
        {:approving_users_count => self.votes.select{|v| v.approved?; v.approved?}.count,
        :disapproving_users_count => self.votes.select{|v| !v.approved?}.count},
        :without_protection=>true
      )
      self.destroy if self.approving_users_count.zero?
    end
  end
end

app/models/ragnarok2/citizen_drop_user.rb
module Ragnarok2
  class CitizenDropUser < ActiveRecord::Base
    belongs_to :user
    belongs_to :citizen_drop, :inverse_of => :citizen_drop_users

    validates :citizen_drop_id,
            :uniqueness => {
              :scope => :user_id
            }

    after_save :update_counter_cache
    after_destroy :update_counter_cache

    private
    def update_counter_cache
      self.citizen_drop.update_user_counter_cache! 
    end
  end
end

app/models/ragnarok2/citizen_item.rb
module Ragnarok2
  class CitizenItem < ActiveRecord::Base
    attr_accessible :item, :buy_type, :max

    belongs_to :citizen, :inverse_of => :citizen_items
    belongs_to :item, :inverse_of => :citizen_items

    validates :item, :citizen, :presence => true
  end
end

app/models/ragnarok2/craft_info.rb
module Ragnarok2
  class CraftInfo < ActiveRecord::Base
    default_scope includes(:craft_materials)
    has_many :craft_materials,
          :primary_key => :craft_info_id,
          :foreign_key => :craft_info_id,
          :dependent => :destroy

    belongs_to :item,
          :foreign_key => :craft_item_id,
          :primary_key => :item_id,
          :inverse_of => :craft_infos

    has_one :craft_scroll,
          :primary_key => :craft_info_id,
          :dependent => :destroy

    default_scope includes(:craft_scroll_item)
    has_one :craft_scroll_item,
          :through => :craft_scroll,
          :source => :item

    alias_method :materials, :craft_materials
  end
end

app/models/ragnarok2/craft_material.rb
module Ragnarok2
  class CraftMaterial < ActiveRecord::Base
    belongs_to :craft_info,
          :primary_key => :craft_info_id,
          :inverse_of => :craft_materials
    belongs_to :item,
          :inverse_of => :craft_materials
    belongs_to :material,
          :class_name => "Ragnarok2::Item",
          :inverse_of => :craft_ingredients

    validates :item, :material, :craft_info, :presence=>true
    validates :amount, :numericality => { :only_integer => true, :greather_than => 0 }
  end
end

app/models/ragnarok2/craft_scroll.rb
module Ragnarok2
  class CraftScroll < ActiveRecord::Base
    validates :item_id,
        :allow_blank => false,
        :numericality => { :only_integer => true }
    validates :craft_info_id,
        :allow_blank => false,
        :numericality => { :only_integer => true }

    belongs_to :item,
        :inverse_of => :craft_scrolls,
        :primary_key => :item_id,
        :foreign_key => :item_id

    belongs_to :craft_info,
        :primary_key => :craft_info_id,
        :inverse_of => :craft_scroll_item
  end
end

app/models/ragnarok2/dungeon.rb
module Ragnarok2
  class Dungeon < ActiveRecord::Base
    validates :dungeon_id,
        :uniqueness => { :case_sensitive => false },
        :allow_blank => false,
        :numericality => { :only_integer => true }

    has_many :map_dungeons, :dependent => :destroy
    has_many :maps, :through => :map_dungeons
    has_many :dungeon_quests,
        :dependent => :destroy
    belongs_to :quest

    scope :default_order, order("ragnarok2_dungeons.name ASC, ragnarok2_dungeons.map_level ASC")

    after_save :update_maps

    def to_s
      self.name
    end

    def to_param
      "#{self.id}-#{self.name.parameterize}"
    end

    def quest_id=(quest_id)
      quest_id = nil if quest_id.to_i.zero?
      super
    end

    private
    def update_maps
      return unless maps_changed?

      self.map_dungeons.destroy_all
      self.maps = Map.where(:map_id=>[self.map_index1, self.map_index2, self.map_index3])
    end

    def maps_changed?
      self.map_index1_changed? || self.map_index2_changed? || self.map_index3_changed?
    end
  end
end

app/models/ragnarok2/dungeon_quest.rb
module Ragnarok2
  class DungeonQuest < ActiveRecord::Base
    validates :quest_id,
        :uniqueness => { :case_sensitive => false },
        :allow_blank => false,
        :numericality => { :only_integer => true }

    validates :mission_name, :presence => true

    belongs_to :dungeon, :inverse_of => :dungeon_quests

    def to_s
      self.mission_name
    end
  end
end

app/models/ragnarok2/item.rb
module Ragnarok2
  class Item < ActiveRecord::Base
    searchable

    validates :item_id,
        :uniqueness => { :case_sensitive => false },
        :allow_blank => false,
        :numericality => { :only_integer => true }

    validates :name, :presence => true

    default_scope includes(:name)
    belongs_to :name,
            :foreign_key => :string_item_name,
            :primary_key => :item_id,
            :class_name => "Ragnarok2::Translations::ItemName"

    default_scope includes(:description)
    belongs_to :description,
            :foreign_key => :string_item_description,
            :primary_key => :item_id,
            :class_name => "Ragnarok2::Translations::ItemDescription"

    belongs_to :category,
            :inverse_of => :items,
            :foreign_key => :category_id,
            :class_name => "Ragnarok2::ItemCategory",
            :counter_cache => true

    default_scope includes(:cash_shop_info)
    belongs_to :cash_shop_info,
            :inverse_of => :item,
            :foreign_key => :item_id,
            :primary_key => :item_id,
            :class_name => "Ragnarok2::ItemCashInfo"

    has_many :quest_item_rewards, :dependent => :destroy
    has_many :quests, :through => :quest_item_rewards

    has_many :citizen_items, :dependent => :destroy
    has_many :sellcitizens,
            :through => :citizen_items,
            :class_name => "Ragnarok2::Citizen",
            :source => :citizen

    has_many :main_set_items,
            :foreign_key => :item_1_id,
            :class_name => "Ragnarok2::SetItem",
            :dependent => :destroy

    has_many :alternative_set_items,
            :foreign_key => :item_2_id,
            :class_name => "Ragnarok2::SetItem",
            :dependent => :nullify

    has_many :main_sets,
            :through => :main_set_items,
            :source => :item_set
    has_many :alternative_sets,
            :through => :alternative_set_items,
            :source => :item_set

    has_many :traits,
            :foreign_key => :item_id,
            :primary_key => :item_id

    has_many :item_break_results,
            :primary_key => :item_break_result_id,
            :foreign_key => :result_id,
            :order => 'grade ASC'

    default_scope includes(:skill)
    belongs_to :skill,
            :primary_key => :skill_id,
            :foreign_key => :skill_id_1

    has_many :item_jobs, :dependent => :destroy
    default_scope includes(:jobs)
    has_many :jobs, :through=>:item_jobs

    has_many :citizen_drops,
            :dependent => :destroy
    has_many :dropcitizens,
            :through => :citizen_drops,
            :class_name => "Ragnarok2::Citizen",
            :source => :citizen

    has_many :craft_infos,
            :foreign_key => :craft_item_id,
            :primary_key => :item_id

    has_many :craft_materials,
            :through => :craft_infos

    has_many :craft_ingredients,
            :class_name => "Ragnarok2::CraftMaterial",
            :foreign_key => :material_id

    has_many :random_sets,
            :primary_key => :randomset_id,
            :foreign_key => :random_set_id,
            :dependent => :destroy

    has_many :random_set_items,
            :through => :random_sets,
            :source => :item

    has_many :found_in_boxes,
            :foreign_key => :item_id,
            :primary_key => :item_id,
            :class_name => "Ragnarok2::RandomSet"


    has_many :craft_scrolls,
            :primary_key => :item_id,
            :foreign_key => :item_id,
            :dependent => :destroy

    has_many :craft_info_scrolls,
            :through => :craft_scrolls,
            :source => :craft_info

    default_scope includes(:item_socket_group)
    has_one :item_socket_group,
            :foreign_key => :socket_group_id,
            :primary_key => :socket_groupid

    has_many :upgrade_infos,
            :through => :item_upgrade_info,
            :conditions => proc { "normalenforcefailed = 1" }

    has_one :item_upgrade_info,
            :primary_key => :item_id

    alias_method :drops, :citizen_drops

    before_save :update_icon_name, :update_required_joblist

    scope :default_order, order("ragnarok2_items.require_level ASC, ragnarok2_translations_item_names.translation ASC")

    scope :search_by_name, lambda {|name|
        where("ragnarok2_translations_item_names.translation LIKE ?", "%#{name}%")
    }

    search_for :name, :as => :string do |b, q|
        b.joins{name.inner}.where{name.translation =~ "%#{q}%"}
    end
    search_for :min_level, :as => :integer do |b, q|
        b.where{require_level.gteq q}
    end
    search_for :max_level, :as => :integer do |b, q|
        b.where{require_level.lteq q}
    end
    search_for :job, :as => :collection, :collection => Proc.new {
        Ragnarok2::Job.all.collect{|j| [j.to_s, j.id]}
        }, :collection_options => {:include_blank => 'All'} do |b, q|
        b.joins{jobs}.group{id}.where{{jobs=>{id=>q}}}
    end 

    def citizens
        self.sellcitizens+self.dropcitizens
    end

    def to_s
      "#{self.name}"
    end

    def to_param
      "#{self.id}-#{self.name.to_s.parameterize}"
    end

    def categories
        high_category, medium_category, low_category = nil
        high_category = ItemCategory.where(:high_category=>self.high_category_id, :medium_category=>0, :low_category=>0).first
        
        unless self.medium_category_id.zero?
        medium_category = ItemCategory.where(:high_category=>self.high_category_id, :medium_category=>self.medium_category_id, :low_category=>0).first
        end
        
        unless self.low_category_id.zero?
        low_category = ItemCategory.where(:high_category=>self.high_category_id, :medium_category=>self.medium_category_id, :low_category=>self.low_category_id).first
        end

        [high_category, medium_category, low_category].compact
    end

    def sockets
        item_socket_group && item_socket_group.sockets || []
    end

    private 

    def update_icon_name
        return unless self.icon_changed?
        name = self.icon.scan(/[^\\\/]+\.dds/).first
        name = name.gsub(".dds", "").downcase if name
        self.icon = name
    end

    def update_required_joblist(force=false)
        return unless self.require_job_changed? || force

        jobs = []
        self.require_job.to_s(2).reverse.split("").each_with_index do |enabled, job_id|
          jobs << job_id+1 unless enabled.to_i.zero?
        end
        self.jobs = Ragnarok2::Job.where(:job_id=>jobs)
    end
  end
end

app/models/ragnarok2/item_break_result.rb
module Ragnarok2
  class ItemBreakResult < ActiveRecord::Base


    def results
      [
        {
          :item=>Ragnarok2::Item.where(:item_id=>self.result_item_1_id).first,
          :amount => self.result_item_1_amount,
          :rate => self.result_item_1_rate
        },
        {
          :item=>Ragnarok2::Item.where(:item_id=>self.result_item_2_id).first,
          :amount => self.result_item_2_amount,
          :rate => self.result_item_2_rate
        }
      ].delete_if {|r| r[:item].nil?}
    end

    def helper_item
      Ragnarok2::Item.where(:item_id=>self.needed_item_id).first
    end

  end
end

app/views/ragnarok2/items/_item.html.haml
%div[item]{:class=>[:item, :model_listing, cycle("odd", "even")]}
  .description= simple_format(ragnarok2_human_description(item.description))
  .model_icon= link_to ragnarok2_icon_image_tag(item.icon, :alt=>""), item
  .model_name
    = link_to item, item
  - unless item.require_level.zero?
    .attribute Required Level: #{item.require_level}
  - unless item.jobs.empty?
    .requirement Job: #{item.jobs.join(", ")}
  - if item.skill && item.skill.description
    .attribute Effect: #{ragnarok2_human_description(item.skill.description)}
  - if item.cash_shop_info
    .attribute
      %span.cashshop CashShop-Item
      = surround '(', ')' do
        = human_cash_shop_duration(item.cash_shop_info)
  - unless item.sockets.empty?
    .attribute= pluralize(item.sockets.count, "Socket")

app/views/ragnarok2/items/index.html.haml
= render "share/searchable", :q => Ragnarok2::Item

= render @items
= render "share/pagination", :entries => @items

app/views/ragnarok2/items/show.html.haml
.model_details.item
  .header
    .model_icon= ragnarok2_icon_image_tag(@item.icon, :alt=>@item.name)
    %h2= @item
    .categoryies
      =raw @item.categories.collect{|c| link_to c, c}.join(" &#187; ")

    - if @item.description
      .description= ragnarok2_human_description @item.description

  .twin_boxes
    .box_left
      .box
        - unless (@item.main_sets+@item.alternative_sets).empty?
          .title Part of
          - (@item.main_sets+@item.alternative_sets).each do |set|
            .item_set
              = link_to set, set
          %br

        .title Requirements
        .requirements
          - unless @item.require_level.zero?
            .requirement Level: #{@item.require_level}
          - unless @item.require_sex.zero?
            .requirement Gender: #{human_gender(@item.require_sex)}
          - unless @item.jobs.empty?
            .requirement Job: #{@item.jobs.join(", ")}
          - if @item.require_level.zero? && @item.require_sex.zero? && @item.jobs.empty?
            .requirement None
      .box
        .title Properties
        .twin_boxes
          .box_left
            - unless @item.price_buy.zero?
              .attribute Price #{@item.price_buy} (buy), #{(@item.price_buy/10.0).ceil} (sell)
            - unless @item.sockets.empty?
              .property= pluralize(@item.sockets.count, "Socket")
            .attribute #{pluralize @item.stack_max, "piece"} stackable
            .attribute Durability #{human_item_durability(@item.durability)}
            .attribute= booleanize_string("Droppable", @item.is_drop)
            .attribute= booleanize_string("Depositable", @item.is_deposit)
            .attribute= booleanize_string("Destructable", @item.is_destruct)
            .attribute= booleanize_string("Sellable", @item.is_sell)
            .attribute= booleanize_string("Tradable", @item.is_trade)
            .attribute= booleanize_string("Composable", @item.is_compose)

          .box_right
            - if @item.cash_shop_info
              .property
                %span.cashshop CashShop-Item
                = surround '(', ')' do
                  = human_cash_shop_duration(@item.cash_shop_info)
                
            - unless @item.traits.empty?
              - @item.traits.each do |trait|
                .property= render trait

        
      - if @item.skill
        = render @item.skill

      - unless @item.upgrade_infos.empty?
        .box
          .title Refining
          - @item.upgrade_infos.each do |upgrade|
            .upgrade_info              
              Level #{upgrade.upgrade_level+1}:
              +#{upgrade.normalabilityuppercent.to_f/100}% Atk/Def
              
              = surround "(", ")" do
                = upgrade.need_normal_material_amount
                = succeed "," do
                  = link_to upgrade.normal_material.to_s.pluralize(upgrade.need_normal_material_amount), upgrade.normal_material
                = succeed "," do
                  = pluralize upgrade.need_zenny, "Rupee"
                #{upgrade.normalenforcerate.to_f/100}% success

      - @item.craft_infos.each do |craft_info|
        .box
          .title Can be crafted by
          .craft_infos=render craft_info

      - unless @item.craft_ingredients.empty?
        .box
          .title Material for
          - @item.craft_ingredients.each do |i|
            .craft_ingredients
              = link_to i.craft_info.item, i.craft_info.item
              = surround "(", ")" do
                = pluralize i.amount, "piece"

      - unless @item.craft_info_scrolls.empty?
        .box
          .title Used for crafting
          - @item.craft_info_scrolls.each do |craft_info|
            = render craft_info


    .box_right
      - unless @item.quest_item_rewards.empty?
        .box
          .title Given as quest reward
          - @item.quest_item_rewards.each do |reward|
            .questreward
              = link_to(reward.quest, reward.quest)
              (#{pluralize(reward.amount, "piece")})

      - unless @item.sellcitizens.empty?
        .box
          .title Buyable at
          .merchant_list.twin_boxes
            - @item.sellcitizens.default_order.each do |citizen|
              .merchant{:class=>cycle("box_left", "box_right", :name => "merchant_list_boxes")}
                .name= link_to citizen, citizen


      - unless @item.random_sets.empty?
        .box
          .title Includes
          .twin_boxes
            - @item.random_sets.each do |item|
              %div{:class=>cycle("box_left", "box_right", :name => "random_sets_boxes_includes")}
                = render item

      - boxes = @item.found_in_boxes.select {|box| !box.boxes.empty? }
      - unless boxes.empty?
        .box
          .title Included in
          .twin_boxes
            - boxes.each do |box|
              - box.boxes.each do |b|
                .ragnarok2_random_set{:class=>cycle("box_left", "box_right", :name => "random_sets_boxes_included")}
                  .random_set_icon= ragnarok2_icon_image_tag(b.icon, :alt=>"")
                  .name
                    = link_to b, b
                    - if box.setbox_type.zero?
                      = surround "(", ")" do
                        random
                  .description
                    = pluralize box.package, "piece"
                    - if box.setbox_type.zero?
                      = surround "(", ")" do
                        #{box.ratio.to_f/1000}%

      .box
        .tools
          = link_to "» Add monsters", new_drop_path(:item_id=>@item.id) 
        .title Drops from / Gathered from
        - if @item.drops.empty?
          .drop Nothing
        - else 
          .twin_boxes
            - @item.drops.default_order.each do |drop|
              .drop{:class=>cycle("box_left", "box_right", :name => "random_sets_boxes_includes")}
                = render drop

  - unless @item.item_break_results.empty?
    .box
      .title Breaks into
      .break_results
        - @item.item_break_results.each do |break_result|
          = render break_result

= render "/share/development_box", :model => @item